### PR TITLE
fix: allow stringified `private` property in `package.json`

### LINKED ISSUE #430: "Invalid contents for file" error when a `package.json` includes `private: "true"`
Based on the findings from https://github.com/mscharley/dependency-changesets-action/issues/428, when a `package.json` file has a stringified boolean in the `private` property (e.g. `private: "true"` or `private: "false"`) the following error appears in CI:

```
RangeError: Invalid contents for file org/repo#path/to/package.json
```

### PR DESCRIPTION
**Pull request by breadadams**
- Update the `isNpmPackage` helper to include the ability for `private` to be `'true' | 'false` in addition to `boolean` (to match [the schema](https://github.com/SchemaStore/schemastore/blob/6d3e056761425e2821c1ee03d39e7d5264fcc3dc/src/schemas/json/package.json#L920-L933)).
- Update `processPullRequest` to handle `private` being a string.

Closes #430

### CODE REVIEW

File: src/model/NpmPackage.ts [hunk 1]
```diff
@@ -1,12 +1,22 @@
...
-import type { GuardedType } from 'generic-type-guard';
+import {
+	type GuardedType,
+	isArray,
+	isBoolean,
+	IsInterface,
+	isString,
+	isUnion,
+	type TypeGuard,
+} from 'generic-type-guard';
```
Comment (breadadams) [inline src/model/NpmPackage.ts:10]: Linter started complaining here about a-z sorting, couldn't resolve it without merging the type imports into the module ones.

File: src/processPullRequest.ts
Comment (breadadams) [inline src/processPullRequest.ts:1]: I wanted to update the unit tests to cover the changes however since the part where the file is read is mocked I couldn't.

Any suggestions are more than welcome @mscharley

Comment (mscharley) [reply src/processPullRequest.ts:1]: The file reading itself is mocked, but it the file contents is still returned, you should be able to return a file which has the `"true"` and `"false"`  values to test this change, right?

**Review by mscharley — COMMENTED** [review]
You'll also need to run `pnpm run all` to rebuild the `dist/` folder before I can accept this. Unfortunately Github Actions need to have the built version committed into the repo.

File: src/model/NpmPackage.ts [hunk 2]
```diff
@@ -1,12 +1,22 @@
...
+
+const isBooleanString: TypeGuard<'true' | 'false'> = (s: unknown): s is 'true' | 'false' =>
+	typeof s === 'string' && ['true', 'false'].includes(s);
```
[the remark this answers is not in the document]
Comment (breadadams) [reply src/model/NpmPackage.ts:13]: Ah sweet, I looked through the available methods but didn't spot this one.

Nice library btw 💯

File: src/processPullRequest.ts
Comment (breadadams) [reply src/processPullRequest.ts:1]: > This wasn't a bug due to complexity, it was a bug caused by a misunderstanding and mismatch of what values needed to be allowed.

Good point, and agree that `generic-type-guard` is well tested.

I've added a test however simply to cover the new ternary logic where I'm checking whether `private` is a string.
